version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.15
    working_directory: /home/circleci/tableroll
    steps:
    - checkout
    - run:
        name: Run unit tests
        command: |
          go test -race ./...
