name: lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
      - uses: HatsuneMiku3939/direnv-action@68bdc19f46a32f049a01c2ea233fe7ca017e8840 # v1
      - name: direnv allow
        run: direnv allow .
      - name: Lint
        run: direnv exec . make lint
      - name: Check diff
        shell: bash
        run: git diff --exit-code
