name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NGROK_TEST_ONLINE: 1
      NGROK_TEST_LONG: 1
      NGROK_TEST_FLAKEY: 1
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
    - uses: HatsuneMiku3939/direnv-action@68bdc19f46a32f049a01c2ea233fe7ca017e8840 # v1
    - name: direnv allow
      run: direnv allow .
    - name: Test
      run: direnv exec . make test-race COUNT=100
